### ISSUE TITLE
Closed DMs makes ban unusable

### ISSUE THREAD

**Issue by Jet132** [CodeBullet-Community/BulletBot#65]
**Describe the bug**
When you try to ban someone that has closed DMs the bot errors because it can't send a DM to that user. This probably is also the case for other moderation commands.

**To Reproduce**
1. Find a user with closed DMs
2. Try to ban him

**Expected behavior**

**Setup (please complete the following information):**
 - Release Version 1.2.8

**Solution**
This can probably be fixed by a simple try-catch

**Comment by geniusjam** [comment]
This was fixed with [this commit](https://github.com/CodeBullet-Community/BulletBot/commit/7b00bc78646f2ac5d9c376c38c6cb5d17f1c8d18#diff-1d1fb4f1613b35a2c68af12ae11c34cc)

**Comment by Jet132** [comment]
yeah. I'll check the issue so it includes all moderation commands as those can still throw errors
